### PR TITLE
feat(web): update docs for beforeValueChange

### PR DESCRIPTION
**Pull request by ShahAnuj2610**

### CODE REVIEW

**Review by bietkul — CHANGES_REQUESTED** [review]
@ShahAnuj2610 You also need to update the `beforeValueChange` in the advanced section.

**Comment by ShahAnuj2610** [comment]
@bietkul have done the changes.

**Review by bietkul — CHANGES_REQUESTED** [review]
@ShahAnuj2610 There are some changes in the specs which you need to update at all places, I updated the message for `RangeInput` in the `v2` branch.

ded

**Comment by ShahAnuj2610** [comment]
> @ShahAnuj2610 There are some changes in the specs which you need to update at all places, I updated the message for `RangeInput` in the `v2` branch.
> 
> ded

@bietkul  Shouldn't the error message be `Start value must be less than or equal to 3000`?

**Comment by ShahAnuj2610** [comment]
@bietkul have updated the docs for web

**Comment by bietkul** [comment]
> > @ShahAnuj2610 There are some changes in the specs which you need to update at all places, I updated the message for `RangeInput` in the `v2` branch.
> > ded
> 
> @bietkul Shouldn't the error message be `Start value must be less than or equal to 3000`?

Right

**Review by bietkul — APPROVED** [review]

**Pull request merged**
