### PR TITLE
fix: data browser gifs and pics

### PR DESCRIPTION
**Pull request by ShahAnuj2610**

### CODE REVIEW

**Comment by jyash97** [comment]
Images look good. But the gifs are blur can we have better quality gif?

**Review by jyash97 — COMMENTED** [review]
Images look good. But the gifs are blur can we have better quality gif?

**Comment by ShahAnuj2610** [comment]
@jyash97 hosted the images on github, there were issues with quality on `imgur` and `giphy`

**Comment by siddharthlatest** [comment]
@jyash97 You can review and merge this. We need a better solution for handling the `src/data/search.index.json` file changes.

**Comment by ShahAnuj2610** [comment]
Noticed today, git has stopped supporting URLs like this:
https://github.com/ShahAnuj2610/gifs/blob/master/add_data.gif?raw=true

**Pull request closed without merging**
