### PR TITLE
Feat/searchbase docs

### PR DESCRIPTION
**Pull request by ShahAnuj2610**

### CODE REVIEW

**Review by jyash97 — COMMENTED** [review]
Hey @ShahAnuj2610 
You will manually need to add links on Navbar and also on HomePage Guides section. 

Also on the content, I think there can be some improvements we should add some description about what searchbase is, what it can do and why to use searchbase with react over reactivesearch. Lets wait for @bietkul  review on content before making changes.

**Review by bietkul — CHANGES_REQUESTED** [review]
1. I don't think we should put it with appbase-js. We can put it under the ReactiveSearch section (header) as Headless or something.
2. Change `Library Integrations` to just `Integrations`.
3. Create and embed code sandbox examples with explanation in `Integrations` section. Refer RS docs.
4. Make the `Integrations` section as a link which can have sub links like `Vanilla`, `React` & `Third Party libraries`.
5. Improve the content of the examples, explain it in a way that one can copy/paste and build the basic search.
For example, this code is incomplete.
alt text
6. It'll be better if you can follow the pattern of ReactiveSearch and format the specs in the same way, I'll update the content later.
alt text

**Comment by bietkul** [comment]
@ShahAnuj2610 Can you resolve the conflicts?
Also when I'm trying to open https://deploy-preview-45--appbase-docs.netlify.com/docs/reactivesearch/searchbase/quickstart/ it gives `404`.

**Comment by ShahAnuj2610** [comment]
> @ShahAnuj2610 Can you resolve the conflicts?
> Also when I'm trying to open https://deploy-preview-45--appbase-docs.netlify.com/docs/reactivesearch/searchbase/quickstart/ it gives `404`.

@bietkul done
route: https://deploy-preview-45--appbase-docs.netlify.com/docs/reactivesearch/searchbase/overview/QuickStart/

**Comment by bietkul** [comment]
@ShahAnuj2610 I don't see you made all the changes.
You completely missed out the 5 & 6 points.

One question:
Are codesandbox examples direct linked to the GitHub repo?

**Review by bietkul — CHANGES_REQUESTED** [review]
@ShahAnuj2610 I don't see you made all the changes.
You completely missed out the 5 & 6 points.

One question:
Are codesandbox examples direct linked to the GitHub repo?

**Comment by ShahAnuj2610** [comment]
> Are codesandbox examples direct linked to the GitHub repo?

yes
> 5 => since we have integrated codesandbox example, the code can be directly copy-pasted from there
> 6 => Getters is a specific property only for classes, so have created a separate section for it, so that it is easily accessible

**Comment by bietkul** [comment]
> 6 => Getters is a specific property only for classes, so have created a separate section for it, so that it is easily accessible

But we have to explain the properties.
Define it in the same way.

alt text

**Pull request merged**
